=== juangarcia-ftw/40260/xml/gramatica.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT programa (variable, ciclo, condicional)>

<!ELEMENT variable EMPTY>
<!ATTLIST variable
    nombre CDATA #REQUIRED
    valor  CDATA #REQUIRED
>

<!ELEMENT ciclo (sumar, mostrar+)>
<!ATTLIST ciclo
    veces CDATA #REQUIRED
>

<!ELEMENT sumar EMPTY>
<!ATTLIST sumar
    a         CDATA #REQUIRED
    b         CDATA #REQUIRED
    resultado CDATA #REQUIRED
>

<!ELEMENT mostrar EMPTY>
<!ATTLIST mostrar
    value CDATA #IMPLIED
    valor CDATA #IMPLIED
>

<!ELEMENT condicional (mostrar+)>
<!ATTLIST condicional
    nombre CDATA #REQUIRED
    valor  CDATA #REQUIRED
>

=== juangarcia-ftw/40260/xml/gramatica.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gramatica SYSTEM "gramatica.dtd">

<programa>
    <variable nombre="x" valor="5"/>
    
    <ciclo veces="3">
        <sumar a="x" b="1" resultado="x"/>
        <mostrar value="Valor de x:"/>
        <mostrar value="x"/>
    </ciclo>

    <condicional nombre="x" valor="8">
        <mostrar valor="x llegó a 8"/>
    </condicional>
</programa>
